### ISSUE TITLE
ImportError: DLL load failed: the specified module could not be found.

### ISSUE THREAD

**Issue by birdjumper** [jnaviask/slicer#1]
Hi

I'm trying to use slicer.py but at the moment I'm getting:
ImportError: DLL load failed: the specified module could not be found.

My system is Win7 64 bit running Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32

My pip installs are:
C:\Python27\pip>pip list
numpy (1.11.0)
pip (8.1.1)
scipy (0.17.0)
setuptools (20.7.0)
vboxapi (1.0)
wheel (0.29.0)

Any idea how to solve this?

Thanks

birdjumper

C:\Python27\test\audio>python slicer.py audio.wav
Traceback (most recent call last):
  File "slicer.py", line 8, in <module>
    import scipy.io.wavfile as sp
  File "C:\Python27\lib\site-packages\scipy\io__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "C:\Python27\lib\site-packages\scipy\io\matlab__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "C:\Python27\lib\site-packages\scipy\io\matlab\mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "C:\Python27\lib\site-packages\scipy\io\matlab\miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "C:\Python27\lib\site-packages\scipy\misc__init__.py", line 51, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "C:\Python27\lib\site-packages\scipy\special__init__.py", line 627, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: the specified module could not be found.

**Comment by jnaviask** [comment]
You probably don't want to use this tool (slicer.py) anyway. It doesn't work. I should do some research and try again sometime.

But looks like http://stackoverflow.com/questions/22753695/dll-load-failed-with-scipy-optimize -- you need to install NumPy-1.11+MKL rather than just base NumPy.

**Comment by birdjumper** [comment]
thanks for the reply. If it doesn't work, maybe you should note that somewhere fairly prominent before someone like me starts trying to use it ...
